### ISSUE TITLE
Add code comments (to create usable API documentation)

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/squid-js#79] opened 2018-12-14 17:06 UTC
It would be necessary to document all the public methods implemented in the Trilobite release. The intention of this is to allow the developers to integrate this API without making necessary to go thru integration tests or similar.

@ttmc could you define what is the best way to document the API to make this documentation available in the docs website?

This is @ttmc writing now. The first step is to add code comments to the squid-js source code, following the syntax given in the TypeDoc docs:

http://typedoc.org/guides/doccomments/

Include:
* The intention of the method
* Input parameters and data types, data formats (i.e if is a did should include or not the 0x)
* Output
* Exceptions raised in the code

The second step is to take the documentation generated by TypeDoc and get it into the docs site somehow, but that is a separate issue: oceanprotocol/docs#45

**Comment by ttmc** [comment] 2018-12-17 09:17
This issue is basically the same as https://github.com/oceanprotocol/docs/issues/45
See the discussion on that issue.

Summary: @kremalicious was looking into it but then higher-priority things came up (such as updating the main oceanprotocol.com website).

As far as I know, there aren't many comments in the squid-js code (TypeScript source code), so adding comments would be a good start.

**Comment by H34D** [comment] 2018-12-17 10:14
Not much comments but a fully working `typedoc` pipeline generating the documentation. Once someone adds some comments they will be generated to a web base documentation.

**Comment by kremalicious** [comment] 2018-12-17 15:49
this issue should be closed in favor of oceanprotocol/docs#45.

See my [comment on there](https://github.com/oceanprotocol/docs/issues/45#issuecomment-441274571), and [the last one](https://github.com/oceanprotocol/docs/issues/45#issuecomment-442507267) about the strategy.

Either we get TypeDoc to generate a proper json file, or we upload the HTML output as a last resort, and both would be handled on the docs repo.

**Comment by ttmc** [comment] 2018-12-18 12:00
There really are two issues:

1. Put comments in the squid-js source code. That would be done by people familiar with squid-js, so it makes sense to have it as an issue in the squid-js repo.
2. Get a pipeline set up to get the TypeDoc-generated output into the docs site. That would be done by Matthias, probably. That's issue oceanprotocol/docs#45.

I will change the title of this issue to reflect its scope as issue number 1.

**Comment by kremalicious** [comment] 2018-12-18 12:20
an issue for the code comments was already added in #80, but it's a duplicate of #68 so with this one here being renamed we now have 3 open issues for the code comments

**Comment by ttmc** [comment] 2018-12-18 12:36
I'll go close those other two issues (duplicated), since this one now has the most commentary and is therefore the most useful for whoever sets out to resolve it.

**Closed** 2019-01-14 14:16 UTC
Labels: documentation
